Implemented  UI-Register-Form with email/password input validation
iOSinternshipen/Internship2022TeamSzabi pull request #1
Opened 2022-07-27 10:04 UTC by ahuzmeza

2022-07-27 10:49 UTC, iOSinternshipen requested changes

2022-07-27 10:49 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +    @IBOutlet weak var registerButton: UIButton!
add a new line between sections, not just here

2022-07-27 10:49 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +    @IBAction func emailCHanged(_ sender: Any) {
typo: emailChanged

2022-07-27 10:49 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +    @IBAction func personal_IDChanged(_ sender: Any) {
avoid "_", use personaldChanged

2022-07-27 10:49 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +    @IBAction func student_IDChanged(_ sender: Any) {
avoid "_"

2022-07-27 10:49 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +    var emailError: String = ""
use private

2022-07-27 10:49 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +    var passwordError: String = ""
use private

2022-07-27 10:49 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +        let email = emailTextField.text!
avoid using "!", instead you can write emailTextField.text ?? ""

2022-07-27 10:49 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +        if textField.text!.isEmpty {
avoid using "!", check for nil or empty

2022-07-27 10:49 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +        return false
you can return just the result of: textField.text!.isEmpty

2022-07-27 10:49 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +        emailError = validateEmail(email) ?? ""
use if emailError then showAlert with email
else if passwordError then showAlert with password
else continue to register

2022-07-27 10:49 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +        if foundEmpty {
use registerButton.isEnabled = !foundEmpty

2022-07-27 10:49 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +    func alertError(_ errors: [String]) {
show alert for only one string

2022-07-27 10:49 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +    // actions
put actions after view did load, they are methods

2022-07-27 10:57 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +    @IBOutlet weak var registerButton: UIButton!
also private outlets / actions

2022-07-27 11:40 UTC, ahuzmeza commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +        if textField.text!.isEmpty {
Can't figure it out. Would appreciate example

2022-07-27 12:25 UTC, IuliaRAnisoi commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +        return true
I believe you can simply write "return textField.text?.isEmpty ?? true"

2022-07-27 12:25 UTC, IuliaRAnisoi commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
>          })
you can remove the handler parameter entirely if you don't use it

2022-07-28 07:05 UTC, IuliaRAnisoi approved these changes

2022-07-28 08:27 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +                addStyleToTextfield(textField: textField as! UITextField)
force unwrap

2022-07-28 08:27 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +        bottomLine.backgroundColor = UIColor(
add color to assets

2022-07-28 08:27 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +        for textField in self.view.subviews {
1. you can use forEach, is similar but more Swifty
2. maybe you can create a custom textfield class to be reused also in Log in screen?

2022-07-28 08:27 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +    @IBOutlet private weak var passwordTextfield: UITextField!
for the password textfield, please use the secure text option, so nobody can see what I'm typing :)

2022-07-28 08:27 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +        let email = emailTextField.text ?? ""
I would use guard, and if nothing is there to show an alert

2022-07-28 08:27 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +        if emailError != ""  {
I would use guard over if

2022-07-28 08:27 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +    func isEmptyTextfield(_ textField: UITextField) -> Bool {
this method is used?

2022-07-28 08:27 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +    func validatePassword(_ password: String) -> String? {
I would make the method private and all the methods that are used only in this class

2022-07-28 13:12 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +        if emailError != ""  {
also use .isEmpty

2022-07-28 13:57 UTC, iOSinternshipen requested changes

2022-07-28 13:57 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +        let emailError = validateEmail(emailTextField.text!)
dont use force unwrap, try emailTextField.text ?? ""

2022-07-28 13:57 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +        let passwordError = validatePassword(passwordTextfield.text!)
dont use force unwrap

2022-07-28 13:57 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +            alertError(passwordError!)
dont use force unwrap

2022-07-28 13:57 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +            alertError(emailError!)
dont use force unwrap, use

2022-07-28 15:10 UTC, IuliaRAnisoi approved these changes

2022-07-29 05:49 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +        view.subviews.forEach { view in
you can move it in a method like setupAppearance or something like that

2022-07-29 05:49 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +        button.layer.shadowOffset = CGSize(
can be on one line

2022-07-29 05:49 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +        bottomLine.frame = CGRect(
same here

2022-07-29 05:49 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
I think you don't set the delegate anywhere

2022-07-29 08:07 UTC, ahuzmeza commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Register/RegisterViewController.swift
> +    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
Removed entirely. It was a temporary fix for keyboard that will be fixed at a later date.

2022-07-29 09:43 UTC, iOSinternshipen approved these changes

2022-07-29 09:49 UTC, merged