Implemented Login UI
iOSinternshipen/Internship2022TeamSzabi pull request #3
Opened 2022-07-27 13:14 UTC by AndreeaBogdan

2022-07-27 13:22 UTC, iOSinternshipen requested changes

2022-07-27 13:22 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Login/LoginViewController.swift
> +        else{
this should be in previous line: "guard condition else { "

2022-07-27 13:22 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Login/LoginViewController.swift
> +        guard let email = emailTextField.text, emailTextField.text?.count != 0
the condition can be just: "emailTextField.text?.count != 0", or even better "!emailTextField.text?.isEmpty"

2022-07-27 13:22 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Login/LoginViewController.swift
> +    @IBAction func loginButton(_ sender: UIButton) {
leave space between arguments and methods, also put buton actions below view did load

2022-07-27 13:22 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Login/LoginViewController.swift
> +        if isValidEmail(emailAddress: email) == false {
use !isValidEmail(emailAddress: email)

2022-07-27 13:22 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Login/LoginViewController.swift
> +            else{
always align else with if

2022-07-27 13:22 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Login/LoginViewController.swift
> +        guard let password = passwordTextField.text,
use "! passwordTextField.text?.isEmpty"

2022-07-27 13:22 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Login/LoginViewController.swift
> +        let bottomLine1 = CALayer()
textfield styling is duplicated, use a method and add the textfield as a parameter

2022-07-27 13:22 UTC, iOSinternshipen commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Login/LoginViewController.swift
> +        loginButton.layer.shadowColor = UIColor(red: 0, green: 0, blue: 0, alpha: 0.25).cgColor
this can be a method for button styling

2022-07-27 13:43 UTC, IuliaRAnisoi requested changes
In your storyboard, you should also remove the width constraints for the "email" and "password" labels. They already have leading and trailing constraints, and adding the width ones cause conflicting constraints errors.

2022-07-27 13:43 UTC, IuliaRAnisoi commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Login/LoginViewController.swift
> +    @IBOutlet weak var loginButton: UIButton!
these should be marked as private (outlets/actions)

2022-07-27 13:43 UTC, IuliaRAnisoi commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Login/LoginViewController.swift
> +        else{
leave a space between else and {

2022-07-27 13:43 UTC, IuliaRAnisoi commented on Internship2022TeamSzabi/Internship2022TeamSzabi/AppDelegate.swift
> +
no need to use self; indent accordingly

2022-07-27 13:43 UTC, IuliaRAnisoi commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Login/LoginViewController.swift
> +            else{
space between else and {

2022-07-27 13:43 UTC, IuliaRAnisoi commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Login/LoginViewController.swift
> +        else{
spacing

2022-07-27 14:56 UTC, IuliaRAnisoi requested changes

2022-07-27 14:56 UTC, IuliaRAnisoi commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Login/LoginViewController.swift
>      }
please indent correctly by selecting this entire block and then use _control+i_

2022-07-27 14:56 UTC, IuliaRAnisoi commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Login/LoginViewController.swift
> +
you should remove the extra lines of spacing between variable declarations

2022-07-27 14:56 UTC, IuliaRAnisoi commented on Internship2022TeamSzabi/Internship2022TeamSzabi/Views/Login/LoginViewController.swift
> +        else {
guard and else statements should be on the same line

2022-07-28 07:03 UTC, IuliaRAnisoi approved these changes

2022-07-28 10:35 UTC, merged